name: RecipeX

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  # flutter_launcher_icons: ^0.11.0
  flutter_riverpod: ^2.1.3
  flutter_svg: ^2.0.5
  go_router: ^6.0.1
  http: ^0.13.5
  intl: ^0.17.0
  lottie: ^2.2.0
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  # flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_lint: ^1.0.1
  custom_lint: ^0.2.11
  flutter_lints: ^2.0.0
# run this command flutter pub run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true


flutter:
  uses-material-design: true
  assets:
    - assets/cert/
    - assets/fonts/
    - assets/images/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins Light 300.ttf
          weight: 300
        - asset: assets/fonts/Poppins Regular 400.ttf
          weight: 400
        - asset: assets/fonts/Poppins Medium 500.ttf
          weight: 500
        - asset: assets/fonts/Poppins SemiBold 600.ttf
          weight: 600
        - asset: assets/fonts/Poppins Bold 700.ttf
          weight: 700
